clear all;
clc;


%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/ranis/Documents/undatathon/arab-subset.xlsx
%    Worksheet: secondary
%
% Auto-generated by MATLAB on 05-Nov-2023 14:51:25

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 41);

% Specify sheet and range
opts.Sheet = "secondary";
opts.DataRange = "A2:AO22";

% Specify column names and types
opts.VariableNames = ["year", "SESECUNERLOFEZS", "SEPRMUNERFEZS", "SEPRMUNERFE", "SLFAMWORKFEZS", "SLAGREMPLFEZS", "SLINDEMPLFEZS", "SLSRVEMPLFEZS", "SEADTLITRFEZS", "SEADT1524LTFEZS", "SESECCMPTLOFEZS", "SHDYNMORTFE", "SHHIV1524FEZS", "SEPRMCMPTFEZS", "SEPREENRRFE", "SETERENRRFE", "SHSTASUICFEP5", "SEPRETCAQFEZS", "SEPRMTCAQFEZS", "SLUEMTOTLFEZS", "SLUEM1524FEZS", "SLEMPWORKFEZS", "SPADOTFRT", "SGGENPARLZS", "EGELCACCSZS", "EGELCACCSRUZS", "EGELCACCSURZS", "SHH2OBASWZS", "SHH2OBASWRUZS", "SHH2OBASWURZS", "SHSTABASSZS", "SHSTABASSRUZS", "SHSTABASSURZS", "SHSTASMSSZS", "SHSTASMSSURZS", "SEPREENRLTCZS", "SEPRMENRLTCZS", "SEPRETCAQZS", "SEPRETCAQFEZS1", "SEPRMTCAQZS", "SEPRMTCAQFEZS1"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
data = readtable("/Users/ranis/Documents/undatathon/arab-subset.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts


T=data(:,2:end)
for i=1:size(T,2)    
test=string(table2array(T(:,i)))
idx=strcmp(test,"..")
test(idx)=nan
idx1=ismissing(test)
test(idx1)="0"
test=double(test);
T.(i)=test;

end

idx1=T.SEPRMCMPTFEZS>75 & T.SEPRMCMPTFEZS<=100;
idx2=T.SEPRMCMPTFEZS>50 & T.SEPRMCMPTFEZS<=75;
idx3=T.SEPRMCMPTFEZS>25 & T.SEPRMCMPTFEZS<=50;
idx4=T.SEPRMCMPTFEZS<=25;

T.primarycomp(idx1)=1; %high
T.primarycomp(idx2)=2 ; %"medium";
T.primarycomp(idx3)=3; %"mediumhigh";
T.primarycomp(idx4)=4%"low";
T.primarycomp=double(T.primarycomp)
% idx1=T.SESECCMPTLOFEZS>75 & T.SESECCMPTLOFEZS<=100;
% idx2=T.SESECCMPTLOFEZS>50 & T.SESECCMPTLOFEZS<=75;
% idx3=T.SESECCMPTLOFEZS>25 & T.SESECCMPTLOFEZS<=50;
% idx4=T.SESECCMPTLOFEZS<=25;
% T.seccomp(idx1)="high";
% T.seccomp(idx2)="medium";
% T.seccomp(idx3)="mediumhigh";
% T.seccomp(idx4)="low";


primary=T(:,1:end-1)

c=corrcoef(table2array(primary,'VariableNames','True'));
s='';
name=T.Properties.VariableNames;
for i=1:length(name)
s=strcat(s,'+',name(i));
end
modelspec='primarycomp~SESECUNERLOFEZS+SEPRMUNERFEZS+SEPRMUNERFE+SLFAMWORKFEZS+SLAGREMPLFEZS+SLINDEMPLFEZS+SLSRVEMPLFEZS+SEADTLITRFEZS+SEADT1524LTFEZS+SESECCMPTLOFEZS+SHDYNMORTFE+SHHIV1524FEZS+SEPRMCMPTFEZS+SEPREENRRFE+SETERENRRFE+SHSTASUICFEP5+SEPRETCAQFEZS+SEPRMTCAQFEZS+SLUEMTOTLFEZS+SLUEM1524FEZS+SLEMPWORKFEZS+SPADOTFRT+SGGENPARLZS+EGELCACCSZS+EGELCACCSRUZS+EGELCACCSURZS+SHH2OBASWZS+SHH2OBASWRUZS+SHH2OBASWURZS+SHSTABASSZS+SHSTABASSRUZS+SHSTABASSURZS+SHSTASMSSZS+SHSTASMSSURZS+SEPREENRLTCZS+SEPRMENRLTCZS+SEPRETCAQZS+SEPRETCAQFEZS1+SEPRMTCAQZS+SEPRMTCAQFEZS1'

 
fitglm(T,modelspec,'Distribution','binomial')
