clear all
clc
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/ranis/Documents/undatathon/arab-subset.xlsx
%    Worksheet: primclean
%
% Auto-generated by MATLAB on 05-Nov-2023 12:18:16

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 28);

% Specify sheet and range
opts.Sheet = "primclean";
opts.DataRange = "A2:AB32";

% Specify column names and types
opts.VariableNames = ["SeriesCode", "SEPRMUNERFEZS", "SEPRMUNERFE", "SLFAMWORKFEZS", "SLAGREMPLFEZS", "SLINDEMPLFEZS", "SLSRVEMPLFEZS", "SEADTLITRFEZS", "SEADT1524LTFEZS", "SHDYNMORTFE", "SHHIV1524FEZS", "SEPRMCMPTFEZS", "SEPREENRRFE", "SHSTASUICFEP5", "SEPRETCAQFEZS", "SEPRMTCAQFEZS", "SLUEMTOTLFEZS", "SLUEM1524FEZS", "SLEMPWORKFEZS", "SEPRETCAQFEZS1", "SEPRMTCAQFEZS1", "SPADOTFRT", "SGGENPARLZS", "EGELCACCSZS", "SHH2OBASWZS", "SHSTABASSZS", "SHSTASMSSZS", "SEPRMTCAQFEZS2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["SEPRETCAQFEZS", "SEPRETCAQFEZS1"], "EmptyFieldRule", "auto");

% Import the data
data= readtable("/Users/ranis/Documents/undatathon/arab-subset.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts
T=data(:,2:end)
for i=1:size(T,2)    
test=string(table2array(T(:,i)))
idx=strcmp(test,"..")
test(idx)=nan
idx1=ismissing(test)
test(idx1)="0"
test=double(test);
T.(i)=test;

end
% name= T.Properties.VariableNames';
% for i=1:length(name)
% idx=isnan(T.(i));
% T.(i)(idx)=0;
% 
% end

% corrplot()

% T.SEPRMCMPTFEZS

idx1=T.SEPRMCMPTFEZS>75 & T.SEPRMCMPTFEZS<=100;
idx2=T.SEPRMCMPTFEZS>50 & T.SEPRMCMPTFEZS<=75;
idx3=T.SEPRMCMPTFEZS>25 & T.SEPRMCMPTFEZS<=50;
idx4=T.SEPRMCMPTFEZS<=25;
% T.primarycomp(:)=0;
T.primarycomp(idx1)=1; %high
T.primarycomp(idx2)=2 ; %"medium";
T.primarycomp(idx3)=3; %"mediumhigh";
T.primarycomp(idx4)=4%"low";
T.primarycomp=double(T.primarycomp)
% idx1=T.SESECCMPTLOFEZS>75 & T.SESECCMPTLOFEZS<=100;
% idx2=T.SESECCMPTLOFEZS>50 & T.SESECCMPTLOFEZS<=75;
% idx3=T.SESECCMPTLOFEZS>25 & T.SESECCMPTLOFEZS<=50;
% idx4=T.SESECCMPTLOFEZS<=25;
% T.seccomp(idx1)="high";
% T.seccomp(idx2)="medium";
% T.seccomp(idx3)="mediumhigh";
% T.seccomp(idx4)="low";


primary=T(:,1:end-1)

c=corrcoef(table2array(primary,'VariableNames','True'))


modelspec ='primarycomp ~ SEPRMUNERFEZS+SEPRMUNERFE+SLFAMWORKFEZS+SLAGREMPLFEZS+SLINDEMPLFEZS+SLSRVEMPLFEZS+SEADTLITRFEZS+SEADT1524LTFEZS+SHDYNMORTFE+SHHIV1524FEZS+SEPRMCMPTFEZS+SEPREENRRFE+SHSTASUICFEP5+SEPRETCAQFEZS+SEPRMTCAQFEZS+SLUEMTOTLFEZS+SLUEM1524FEZS+SLEMPWORKFEZS+SEPRETCAQFEZS1+SEPRMTCAQFEZS1+SPADOTFRT+SGGENPARLZSE+GELCACCSZS+SHH2OBASWZS+SHSTABASSZS+SHSTASMSSZS+SEPRMTCAQFEZS2';

fitglm(T,modelspec,'Distribution','binomial')

